I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 192, in script
    python:
  File "renpy/common/00start.rpy", line 193, in <module>
    renpy.execute_default_statement(True)
  File "game/script.rpy", line 309, in set_default
    default goodAnswers = 0
Exception: store.goodAnswers is being given a default a second time.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 192, in script
    python:
  File "C:\Users\marys\Downloads\renpy-8.0.3-sdk\renpy\ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\marys\Downloads\renpy-8.0.3-sdk\renpy\python.py", line 1061, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00start.rpy", line 193, in <module>
    renpy.execute_default_statement(True)
  File "C:\Users\marys\Downloads\renpy-8.0.3-sdk\renpy\exports.py", line 3797, in execute_default_statement
    i.set_default(start)
  File "game/script.rpy", line 309, in set_default
    default goodAnswers = 0
Exception: store.goodAnswers is being given a default a second time.

Windows-10-10.0.19041 AMD64
Ren'Py 8.0.3.22090809
Leyendas 1.0
Wed Sep 21 23:07:14 2022
